worker_processes auto;

pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    # Logs to Docker log system
    access_log /dev/stdout;
    error_log  /dev/stderr warn;

    # Temp-Verzeichnisse in /tmp, damit User 'application' schreiben darf
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    server {
        listen 80;
        server_name _;
        root /app/webroot; # Only webroot will be served
        index index.php;

        # Dedicated healthcheck endpoint
        location /healthcheck {
            default_type text/plain;
            return 200 "OK\n";
        }

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            try_files $uri =404; # Only forward existing files to PHP
            include fastcgi_params;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass foodcoopshop-app:9000; # Service name from docker-compose.yml
            fastcgi_connect_timeout 60s;
            fastcgi_send_timeout    180s;
            fastcgi_read_timeout    180s;
        }
	    # Static assets (but /photos/ excluded)
        location ~* ^/(js|css|fonts|images)/.*\.(png|jpg|jpeg|gif|svg|ico)$ {
            expires 7d;
            access_log off;
        }
	    # Forward profile pictures explicitly to PHP
        location ^~ /photos/ {
            try_files $uri /index.php?$args;
        }
        # Explicitly deny (although not known to nginx anyway - but better safe than sorry)
        location /files_private {
            deny all;
            return 403;
        }
    }
}
