[global]
; Globale error log goes into Docker log
error_log = /proc/self/fd/2

; PID file (optional for Container)
pid = /usr/local/var/run/php-fpm.pid

; Standard include for pool configs
include=/usr/local/etc/php-fpm.d/*.conf
