[www]
; Pool name (PHP worker are not running as root)
user = application
group = application

; TCP listener for Docker compose service
listen = 9000

; Process management
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Redirect ouput of workers into error log
catch_workers_output = yes

; PHP specific setting
php_admin_flag[log_errors] = on

; Optional: env variables for CakePHP
env[APP_ENV] = production
env[TMP] = /app/tmp
